[package]
name = "dit-voting-blockchain"
version = "1.0.0"
authors = []
edition = "2018"

[dependencies]
exonum = "0.12.1"
exonum-time = "0.12.0"
hex = "0.3.2"
dit-votings-service = { path = "./services/votings-service" }

[profile.release]
lto = true